name: Pyhton CI  # Name of workflow

# Define Events like [push, pull, merge, delete]
#Trigger the workflow on any push to the main branch or pull request to the main branch
on:  
    #Event 1
  push: # Action triggered on push events
    branches: # there can be various branches like [main, develop, staging, production etc.]
      - main
    #Event 2
  pull_request: # Action triggered on pull request events
    branches:
      - main
      # - stagging
      # - production
      # - develop

jobs:
  test:
    runs-on: ubuntu-latest # Latest Containers to run and check like[windows, mac etc ]

    # Define the steps to run in the job
    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2 #Pre build GitHub Action to checkout the code from the repository
        # v2- tells the version: This might change based on preference. 

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10' # Specify the Python version to use.

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

        # Step 4: Run tests
      - name: Run tests
        run: pytest
        # This step runs the tests using pytest. You can modify this command based on your testing framework.
